### ISSUE TITLE
Is this problem resolved？

### ISSUE THREAD

**Issue by programClown** [beeradmoore/AvaloniaWebViewTest#1]

**Comment by beeradmoore** [comment]
Nope


Edit: wait, sorry, I thought this was a different repo also with a webview problem.

I am unsure of this is solved.

**Comment by programClown** [comment]
emmm, cefglue's demo is so unreliable...
I give up used web feature in avalonia 😂

**Comment by beeradmoore** [comment]
I now remember what this repo was for. It was so I could reproduce the issue in [this](https://github.com/OutSystems/WebView/issues/318) thread. 

EDIT: Updated readme so I don't forget what this was for again.

**Comment by beeradmoore** [comment]
@programClown , this is now resolved, see the readme again for changes you need to do to make it work.
